### ISSUE TITLE
Cannot find module 'dexie-relationships'

### ISSUE THREAD

**Issue by christianmls** [ignasbernotas/dexie-relationships#7] opened 2017-02-17 03:16 UTC
Sorry for this, I am new in javascript.

I have a project with Angular 2 generated with angular-cli latest version. and "typescript": "~2.0.0"

I install:

npm install dexie-relationships --save 

and I import:

import relationships from 'dexie-relationships'

When I build with ng serve

ERROR in C:/frontend/src/app/database.ts (2,27): Cannot find module 'dexie-relationships'.)

**Comment by dfahlander** [comment] 2017-02-17 07:02
Your tsconfig.json should have moduleResolution: "node"  for typescript to find node modules. Also, "allowJs" : true  because Dexie-relationships has no typings.

**Comment by christianmls** [comment] 2017-02-17 17:10
Thank you very much, but no work :(, this is tsconfig.json

`{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
	  "allowJs": true,
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}`

**Comment by dfahlander** [comment] 2017-02-17 17:22
@nponiros is experienced in angular2. Maybe he could have a look at it?

**Comment by nponiros** [comment] 2017-02-17 19:04
@christianmls try TypeScript newer than 2.1 (angular-cli uses 2.0). The `allowJs` flag should not be needed. As it seems TypeScript before 2.1 did not allow imports of modules which don't have types, at least not for modules in node\_modules. You could of course define a declaration file to avoid errors in case `noImplicitAny` is used.

**Comment by christianmls** [comment] 2017-02-17 21:33
Thank you very much to all. With 2.1 font this reading module is fine.

But I have a new error

Uncaught TypeError: Dexie.override is not a function

I use Dexie thus: (Dexie version 2.0.0-beta.10)

class NextlimAppDB extends Dexie {
    public _company : Dexie.Table< ICompany, number >
    constructor(){
        super( 'NextlimAppDB', { addons: [ relationships ] } );
   } 
}

I guess it's because of the use of typescript. Thank you very much for your package, it's great, but I couldn't use it :(

**Comment by nponiros** [comment] 2017-02-17 22:02
I'm not familiar with dexie-relationships but generally speaking a TypeError is a JavaScript error (runtime error) and not a TypeScript. No clue why override is not a function (is probably undefined). Perhaps you can try the beta 3 version of dexie as requested by this addon (peer dependency). Maybe I can test tomorrow and let you know what I find.

**Comment by christianmls** [comment] 2017-02-17 22:08
I thank you very much, I hope you can do it.

I tried with

Dexie version 1.5.1
Dexie version 2.0.0-beta.3
Dexie version 2.0.0-beta.10

All versions of Dexie have override method.

**Comment by nponiros** [comment] 2017-02-18 09:59
@christianmls I tried it now but I can't reproduce your issue. Everything works just fine here. I used dexie version 2.0.0-beta.10 and dexie-relationships version 1.2.1. This is my code:

```
import Dexie from 'dexie';
import relationships from 'dexie-relationships';

class MyDB extends Dexie {
  constructor() {
    super('testDB', { addons: [relationships] });
  }
}
```

In some other part I just called `new MyDB()`. Maybe you can provide us with some more code or a stack trace to help us find the issue.

**Comment by christianmls** [comment] 2017-02-18 14:04
Hi, this is my code

import Dexie from 'dexie';
import relationships from 'dexie-relationships';

//Interfaces
import { ICompany } from './interfaces/company.interface';

class NextlimAppDB extends Dexie {
    public _company : Dexie.Table< ICompany, number >

    constructor(){
        super( 'NextlimAppDB', { addons: [ relationships ] });

        this.version(1).stores({
            _company: '++id, &slug, &identification, name, address,  delete',
        });

        this._company.mapToClass( CompanyModel );
    }
};

//Modelos

////////////////////////////////////////////////////////////////////////////////////////////
export class CompanyModel implements ICompany {
    id ?: number;
    slug: string;
    identification : number;
    name : string;
    address : string;
    _delete : boolean;

    constructor( _company: ICompany ) {

        this.identification =  _company.identification;
        this.slug =  _company.slug;
        this.name =  _company.name;
        this.address =  _company.address;
        if( _company._delete ) this._delete = _company._delete;
        if( _company.id ) this.id = _company.id;

    }

    // Guardar
    save() {
        return NextlimDB._company.add( this );
    }

    // Actualizar
    update() {
        return NextlimDB._company.put( this );
    }

    // Recuperar Empresa
    static get() {
      let subdomain = window.location.hostname.split('.').shift();
      return NextlimDB._company.orderBy( 'id' ).limit( 1 ).first();
      //       return NextlimDB._company.orderBy( 'id' ).reverse().toArray();
    }

}


export let NextlimDB = new NextlimAppDB();

**Comment by nponiros** [comment] 2017-02-18 15:04
I don't see any issues in what you are doing here. It seems to be pretty similar to what I did. Can you give us a stack trace of the error so we can perhaps see where the override function is called?

**Comment by christianmls** [comment] 2017-02-18 15:52
Hi,

This is the comple error

Uncaught TypeError: Dexie.override is not a function
    at Relationships (http://127.0.0.1:4200/vendor.bundle.js:103540:49)
    at http://127.0.0.1:4200/vendor.bundle.js:107710:9
    at Array.forEach (native)
    at NextlimAppDB.Dexie (http://127.0.0.1:4200/vendor.bundle.js:107709:12)
    at new NextlimAppDB (http://127.0.0.1:4200/main.bundle.js:181:28)
    at Object.18 (http://127.0.0.1:4200/main.bundle.js:1189:17)
    at __webpack_require__ (http://127.0.0.1:4200/inline.bundle.js:53:30)
    at Object.87 (http://127.0.0.1:4200/main.bundle.js:7481:68)
    at __webpack_require__ (http://127.0.0.1:4200/inline.bundle.js:53:30)
    at Object.686 (http://127.0.0.1:4200/main.bundle.js:5740:84)
    at __webpack_require__ (http://127.0.0.1:4200/inline.bundle.js:53:30)
    at Object.687 (http://127.0.0.1:4200/main.bundle.js:5796:73)
    at __webpack_require__ (http://127.0.0.1:4200/inline.bundle.js:53:30)
    at Object.530 (http://127.0.0.1:4200/main.bundle.js:5624:74)
    at __webpack_require__ (http://127.0.0.1:4200/inline.bundle.js:53:30)
Relationships @ index.js:213
(anonymous) @ dexie.es.js:4137
Dexie @ dexie.es.js:4136
NextlimAppDB @ database.ts:48
18 @ database.ts:1296
__webpack_require__ @ bootstrap 6506ab0…:52
87 @ main.bundle.js:7481
__webpack_require__ @ bootstrap 6506ab0…:52
686 @ invoice-sale.service.ts:10
__webpack_require__ @ bootstrap 6506ab0…:52
687 @ app.component.ts:14
__webpack_require__ @ bootstrap 6506ab0…:52
530 @ src async:7
__webpack_require__ @ bootstrap 6506ab0…:52
947 @ user.service.ts:10
__webpack_require__ @ bootstrap 6506ab0…:52
webpackJsonpCallback @ bootstrap 6506ab0…:23
(anonymous) @ main.bundle.js:1

============================

vendor.bundle.js

db.Version.prototype._parseStoresSpec = Dexie.override(
    db.Version.prototype._parseStoresSpec,
    function (parseStoresSpec) { return function (storesSpec, outDbSchema) {
      var parser = new SchemaParser(storesSpec);

      var foreignKeys = parser.getForeignKeys();
      // call the original method
      var rv = parseStoresSpec.call(this, parser.getCleanedSchema(), outDbSchema);

      // set foreign keys into database table objects
      // to use later in 'with' method
      Object.keys(outDbSchema).forEach(function (table) {
        if (foreignKeys.hasOwnProperty(table)) {
          outDbSchema[table].foreignKeys = foreignKeys[table];
          foreignKeys[table].forEach(function (fk) {
            outDbSchema[table].idxByName[fk.index].foreignKey = fk;
          });
        }
      });

      return rv
    }; });
};

return Relationships;

**Comment by christianmls** [comment] 2017-02-18 16:01
Sorry, I use:
Angular cli 1.0.0-beta.32.3
ng new project

**Comment by nponiros** [comment] 2017-02-18 17:40
I use the same angular-cli version and used ng new. I see no reason why your code should fail. The exception you get is at the position I expected but for whatever reason I don't get that same exception. Can you reproduce the error in another dummy app and give us the code? My guess is that the inheritance chain is not built correctly and that is why override can not be found but I have no clue why the chain should not be built correctly.

You can also try using Dexie with relationships directly without extends like this:

```
import Dexie from 'dexie';
import relationships from 'dexie-relationships';

class MyDB {
  constructor() {
   this.db = new Dexie('testDB', { addons: [relationships] });
  }
}
```

and see if you still get the error.

**Comment by dfahlander** [comment] 2017-02-19 03:05
Now I think I know what's wrong here! It's a stupid line of code that I am responsible for, described in #8.

**Comment by dfahlander** [comment] 2017-02-19 03:52
Fixed in PR #9

**Comment by nponiros** [comment] 2017-02-19 09:32
@dfahlander regarding #8  that is what I thought at the beginning but it worked for me. When deriving a class the static methods like override are also inherited as it seems. So `db.constructor` should work. It did for me unless I made some other mistake..

**Comment by dfahlander** [comment] 2017-02-19 11:51
Aha. True. So strange then. Think it needs to be debugged further by @christianmls who has the entire setup. @christianmls, you can try if my fork of the addon solves it for you. However, there seem to be something wrong in your setup as the code should have worked as is.

**Comment by christianmls** [comment] 2017-02-20 16:31
Hi, good morning, thank for your help in the versión 1.2.2 I have this error:

ERROR in /mnt/c/Users/Christian/Desktop/project/src/app/database-typescript.ts (2,8): Module '"/mnt/c/Users/Christian/Desktop/project/node_modules/dexie-relationships/dist/index"' has no default export.)

When I use dexie-relations in the form of "vanilla" works well.

A repository is created with my code.

https://github.com/christianmls/demo-dexie-relationships

I created 3 examples

Maybe the problem is me, I have little experience in javascript

**Comment by dfahlander** [comment] 2017-02-20 16:49
I think it's due to a miss in my last change, where I added typings for the addon. Thanks for finding this. Please try editing node_modules/dexie-relationships/dist/index.d.ts and add the following to the end of that file:

```ts

declare var dexieRelationships: (db: Dexie) => void;

export default dexieRelationships;
```

Please tell me if it solves it. If so. I'll commit the change and release a new version.

**Comment by christianmls** [comment] 2017-02-20 17:14
thank you very much,

Works in my example project. I test now in my production project.

**Comment by dfahlander** [comment] 2017-02-20 17:20
Thank You for your patience.

**Comment by christianmls** [comment] 2017-02-20 18:02
Thank you very much, it works very well in my production project. It is an excellent library

**Closed** 2017-03-16 10:48 UTC
