### ISSUE TITLE
Problem with relations One-to-many

### ISSUE THREAD

**Issue by christianmls** [ignasbernotas/dexie-relationships#10] opened 2017-02-21 18:41 UTC
Hi,
When I have 2 bands in the same genre

        // Bands
        this.db.table('bands').bulkPut([{
            id: 1,
            name: 'Beatles',
            genreId: 1
        },{
            id: 2,
            name: 'Abba',
            genreId: 2
        },{
            id: 3,
            name: 'The Police',
            genreId: 1
        }])

Recovery only 1 object with same genre.

I found in the code and I discored that line # 182 attribute is foreignKey

For this reason 2 objects can not share the same foreignKey ( lookup[row[targetIndex]] = row; )

Console Log
lookup:  Object {1: Object, 2: Object}

===============
      return Promise.all(queryPromises).then(function (queryResults) {
        foreignTableNames.forEach(function (tableName, idx) {
          var foreignTable = usableForeignTables[tableName];
          var result = queryResults[idx];
          var targetIndex = foreignTable.targetIndex;
          var foreignIndex = foreignTable.index;
          var column = foreignTable.column;

          // Create a lookup by targetIndex (normally 'id')
          // and set the column onto the target
          var lookup = {};
          rows.forEach(function (row) {
            lookup[row[targetIndex]] = row;
          });
          console.log( 'lookup: ', lookup );

          // Populate column on each row
          result.forEach(function (record) {
            var foreignKey = record[foreignIndex];
            var row = lookup[foreignKey];
            console.log( record[foreignIndex] );

**Comment by nybblr** [comment] 2017-03-20 17:19
Same issue. I'm doing a very similar query:

```javascript
let db = new Dexie('MyDB', { addons: [relationships] });
db.version(1).stores({
  albums: `++id,title`,
  songs:  `++id,albumId->albums.id,albumTitle,title,[albumTitle+title]`
});

db.songs.with({album: 'albumId'}).then(console.log)
```

But only the last Song of any particular album gets an `album` property added. A Song "belongs to" an Album, so it's definitely not oneToOne, but many (Songs) to one (Album).

Is that out of scope for this library, user error or a bug? Seems like the oneToMany is the primary "relational" use case, since a oneToOne is typically encoded directly on the "parent" object in a NoSQL db.

Thanks!

**Comment by nybblr** [comment] 2017-03-20 18:09
@dfahlander any thoughts on this? I'm spiking on hacking in one-to-many, but would love to find I was just doing everything wrong 😄

**Comment by dfahlander** [comment] 2017-03-21 01:50
@nybblr Please hack into it :+1:  If you do, please add a test that would reproduce the bug.

**Comment by dfahlander** [comment] 2017-03-21 01:56
@nybblr You're right that what is named as "oneToOne" is not really one-to-one - it's still one-to-many relation but accessed from another perspective. Should be named differently.

**Comment by nybblr** [comment] 2017-03-21 16:10
@dfahlander great! I got it working for oneToMany, but probably broke manyToOne so I'll pull down the test suite later.

**Closed** 2017-03-22 04:58 UTC

**Comment by nybblr** [comment] 2017-03-22 16:54
@dfahlander Whoops, that got merged but without updating dist/index.js. Are you able to rebuild on master?

**Comment by dfahlander** [comment] 2017-03-22 21:07
No probs. Either @ignasbernotas builds it and releases it on npm, or you send a new pr if you like.

**Comment by nybblr** [comment] 2017-03-22 21:27
:+1:

**Comment by dfahlander** [comment] 2017-04-02 19:47
@ignasbernotas Could you please update version to 1.2.4 and release this fix on npm? If you like, you could give me permission on npm to do that.

Note: You need to pull latest master. I've removed dist output from git. So you need to build before releasing on npm.

**Comment by ignasbernotas** [comment] 2017-04-02 19:50
Hi @dfahlander. I've added you to npm's collaborator's list. I'm a bit out of track here on what's going on so I think it makes sense for you to control this package :)

**Comment by dfahlander** [comment] 2017-04-02 20:03
Thanks. Of some strange reason I still get a 403 when trying to npm publish.

**Comment by ignasbernotas** [comment] 2017-04-02 20:08
Hmm, weird.

⇒  npm owner ls
dfahlander <d...@gmail.com>
ignasbernotas <i..@iber.lt>

I remember I had to setup auth credentials when I initially published this, but I can't find what needed doing now.

**Comment by ignasbernotas** [comment] 2017-04-02 20:09
ah, `npm login`. maybe worth a shot trying that:)

**Comment by dfahlander** [comment] 2017-04-02 23:30
I did, with no luck. However, after trying again some hours later, it worked ... npm sync "issue", I believe.
